name = "TestParticleAnalysis"
uuid = "190ac06d-205a-4ff8-8d50-56c31c2b86b9"
authors = ["Beforerr <zzj956959688@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"

[compat]
AlgebraOfGraphics = "0.10.5"
julia = "1.10"
